theme: jekyll-theme-minimal
title: Alex Izydorczyk
description: I am working on something new in Data/Data Science. I previously was the Head of Data Science at Coatue.
google_analytics: UA-54493154-1
